practice-app/frontend/profile.html, practice-app/frontend/styles/main_styles.css
=> Profile page is implemented

practice-app/scholar_util.py
an alternative search author method
get authors pubs method
get citation by year method
search publication method are added
=> scholar_util.py enhancement

practice-app/thirdparty.py
Added paper search functionality
=> thirdparty.py is updated

practice-app/scholar_util.py
Recent publications functionality is implemented.
=> Recent pubs dev

.gitignore, practice-app/scholar_util.py
Code reorganization and bug fixes
=> Code reorganization and bug fixes

practice-app/templates/coronavirus.html
=> coronavirus page

practice-app/backend.py, practice-app/coronavirus_api.py, practice-app/templates/searchCountryName.html
new methods added and minor bugs fixed
=> Coronavirus dev

practice-app/backend.py, practice-app/scholar_util.py
Range parameter for the recent publications is reintroduced.
Exceptions occuring due to missing fields are handled.
=> recent publications bug fix

practice-app/backend.py, practice-app/templates/profile.html
There was multiple occurence of same end point, and a templating syntax error. Both of them are handled.
=> profile page error fix

practice-app/scholar_util.py, practice-app/templates/coronavirus.html, practice-app/templates/coronavirusByCountry.html, practice-app/templates/profile.html, practice-app/templates/worldstats.html
I have updated profiles so that:
- field display `div`s only appear if said field is applicable for user.
- link to the scholar's profile is working
=> fix profiles and set flag width

practice-app/backend.py, practice-app/bitcoin_api.py, practice-app/templates/bitcoin.html, practice-app/templates/home.html, practice-app/templates/rankcoin.html
Lists the most popular 10 cripto currencies.
=> Coin ranks page is implemented

practice-app/backend.py, practice-app/coronavirus_api.py
Added plot.png endpoint for plotting total case no day by day for turkey,
Maybe it can be paramterized for other countries in the future.
=> Added total case country plot,

practice-app/templates/base_template.html, practice-app/templates/bitcoin.html, practice-app/templates/coronavirus.html, practice-app/templates/coronavirusByCountry.html, practice-app/templates/home.html, practice-app/templates/profile.html, practice-app/templates/rankcoin.html, practice-app/templates/search.html, practice-app/templates/searchCountryName.html, practice-app/templates/worldstats.html
=> Navlinks become dropdowns

practice-app/templates/bitcoin.html, practice-app/templates/rankcoin.html
Add navbar links to CryptoCurrency endpoints
Add link to altcoins below BTC price chart
Style altcoin table
=> CryptoCurrency front-end updates

frontend/src/components/PersonRecommendationCard/index.jsx, frontend/src/components/PersonRecommendationCard/style.js, frontend/src/components/ProjectRecommendationCard/index.jsx, frontend/src/components/ProjectRecommendationCard/style.js, frontend/src/pages/Home/index.jsx, frontend/src/pages/Home/style.js
**Intro:**
Home page is created. Home page is where the feed of the user is displayed. Also there are person and project recommendations are made at that page.
**How it is implemented:**
While implementing home page several components are used. Which are:
- Frame Component
- Content Card Component
- Person Recommend Card Component
- Project Recommend Card Component
Person recommend card and project recommend card components are created from scratch. Other two components were already created for search page therefore they are just reused.
**Responsivity:**
Responsivity controls of the home page are also made. You can see the below the related Images.
**Small:**
**Medium:**
**Large:**
=> Home Page is Created

backend/model/database_tables/User_Interests.js, backend/model/database_tables/Users.js, backend/model/db.js, backend/model/interests.js, backend/model/posts.js, backend/model/project_collaborators.js, backend/model/project_files.js, backend/model/project_milestones.js, backend/model/project_tags.js, backend/model/projects.js, backend/model/tags.js, backend/model/user_affiliations.js, backend/model/user_interests.js, backend/model/user_projects.js, backend/model/user_ups.js, backend/model/users_new.js
ORM DB design tables and models are added. Please review the change.
=> ORM DB design is added

frontend/src/components/FilterButton/index.jsx, frontend/src/components/FilterButton/style.js, frontend/src/components/FilterButtonSmall/index.jsx, frontend/src/components/FilterButtonSmall/style.js, frontend/src/pages/Home/index.jsx, frontend/src/pages/Search/index.jsx, frontend/src/pages/Search/style.js
**Intro:**
6 buttons are created and added to the search page. Those buttons are created to allow user to filter the search results. 
**How it is implemented:**
2 components are used.
- FilterButton
- SmallFilterButton
Filter button has to be revised and SmallFilterButton is created from scratch. 
**Responsivity:**
When screen size gets smaller, buttons are moved to the top.
**Small:**
**Medium:**
**Large:**
=> Frontend Search Page Filter Buttons are Created

frontend/src/components/ProfileSider/index.jsx
User id is retrieved from local storage.
=> Get user id from local storage

frontend/src/pages/Profile/index.jsx, frontend/src/pages/SignUp/index.jsx, frontend/src/redux/auth/actions.js, frontend/src/redux/auth/api.js, frontend/src/redux/auth/reducer.js, frontend/src/redux/profile/api.js
After this morning's changes in the backend, signup process and profile page were unfunctional. I patched some small fixes to overcome these problems.
1. Validation success reducer now registers the newly returned token into the local storage
2. Profile endpoint's json structure is changed, the fields were updated accordingly
=> Backend Change Fixes

frontend/src/pages/FileEditor/index.jsx, frontend/src/pages/FileEditor/style.js, frontend/src/routes.jsx
Created project files edit page with dummy data
=> Add project files edit page

frontend/src/pages/Search/index.jsx
I have fixed the bug mentioned in the issue Search Bug #257.
=> Fix Search Bug

frontend/src/redux/choices/reducer.js
Departments list showed universities and universities list showed departments. I fixed the bug.
=> Fix Signup Bug

backend/controllers/collabController.js, backend/controllers/fileController.js, backend/controllers/postController.js, backend/routers/fileRouter.js, backend/routers/postRouter.js
Changed implementation for getting project files from database. Now we're sending one file by one request. And also fixed minor bug in collabController file. Please review.
=> Changed implementation of getting project-files & fixed bug.

backend/controllers/postController.js, backend/util/postUtil.js
Updated those functions, to be able to return tags added before to database as frontend now wishes. Please review.
=> addTag and tagExist Functions are Updated

backend/controllers/autoCompleteController.js
Input validation added for erroronous inputs, please review. #281
=> Added input validation at autocomplete add endpoints

backend/controllers/profileController.js, backend/util/userUtil.js
please review:
googlescholar now uses api
bio can be changed from profile update endpoint as well now.
=> profile update endpoint, google scholar api

frontend/src/pages/CreateProject/index.jsx, frontend/src/pages/EditProject/index.jsx, frontend/src/pages/EditProject/style.js, frontend/src/redux/project/api.js
* Project can now be deleted on the edit project page.
* Fixed bug on project status radio buttons
* Reworked project creation page, it now has less fields
* Now redirecting to project edit after project creation
=> Frontend edit pages

frontend/src/components/MainHeader/index.jsx, frontend/src/components/MainHeader/style.js, frontend/src/components/Notification/index.jsx, frontend/src/components/Notification/style.js
Notification modal is created. 
In order to implement this following components are used:
- Modal component from Ant Design
- Notification component that is created from scratch
Screenshot:
=> Frontend Notification Modal is Created

frontend/package.json, frontend/src/pages/FileEditor/index.jsx, frontend/src/pages/FileEditor/style.js, frontend/yarn.lock
* Connection to backend for file view, upload and delete
=> File viewing, upload and deletion

frontend/src/pages/EditProject/index.jsx, frontend/src/pages/ProjectDetails/index.jsx
- added due date logic and option on the project edit page
- set the confirm button on project edit page to be floating to enhance the UX
=> Frontend Project Edit Duedate

android/Akademise_dev/app/src/main/java/com/example/akademise/AkademiseApi.java, android/Akademise_dev/app/src/main/java/com/example/akademise/GoogleScholar.java, android/Akademise_dev/app/src/main/java/com/example/akademise/GoogleScholarFragment.java, android/Akademise_dev/app/src/main/java/com/example/akademise/GoogleScholarPublication.java, android/Akademise_dev/app/src/main/java/com/example/akademise/GoogleScholarRVAdapter.java, android/Akademise_dev/app/src/main/java/com/example/akademise/Profile.java, android/Akademise_dev/app/src/main/java/com/example/akademise/ProfileActivity.java, android/Akademise_dev/app/src/main/java/com/example/akademise/ProfileFragment.java, android/Akademise_dev/app/src/main/java/com/example/akademise/ProfileOthersFragment.java, android/Akademise_dev/app/src/main/java/com/example/akademise/Url.java, android/Akademise_dev/app/src/main/res/layout/fragment_google_scholar.xml, android/Akademise_dev/app/src/main/res/layout/fragment_profile.xml, android/Akademise_dev/app/src/main/res/layout/fragment_profile_others.xml
=> Android googlescholar

backend/controllers/postController.js, backend/util/postUtil.js, backend/util/userUtil.js
I added attributes to result. Not much thing has changed
=> Backend homepage posts

frontend/src/components/ContentCard/index.jsx, frontend/src/components/PersonRecommendationCard/index.jsx, frontend/src/components/ProjectRecommendationCard/index.jsx, frontend/src/pages/Home/index.jsx
Backend connection of the home page is completed. 
In terms of user recommendations:
- backend connections are made.
- profile redirections are handled.
- necessary styling asjustments are performed.
In terms of project recommendations (aka. feed):
- backend connections are made.
- status label is added.
- necessary styling asjustments are performed.
Example Screenshot:
Due to temporary data user recommendations part looks unprofessional :(
=> Home Page Backend Connection of User and Project Recommendations

android/Akademise_dev/app/src/main/java/com/example/akademise/AkademiseApi.java, android/Akademise_dev/app/src/main/java/com/example/akademise/GoogleScholarFragment.java, android/Akademise_dev/app/src/main/java/com/example/akademise/Home.java, android/Akademise_dev/app/src/main/java/com/example/akademise/HomeFragment.java, android/Akademise_dev/app/src/main/java/com/example/akademise/ProfileOthersFragment.java, android/Akademise_dev/app/src/main/res/layout/fragment_profile.xml, android/Akademise_dev/app/src/main/res/layout/fragment_profile_others.xml
=> home functionality added

frontend/src/pages/FileEditor/index.jsx
* Implemented file editing
* Implemented extension filters to display or not display file
Only accepting following plain text formats for now
`const plainTextExtensions = [".txt", "", ".json", ".md", ".css", ".html", ".js", ".py", ".jsx", ".c"];`
=> Frontend File Editor

android/Akademise_dev/app/src/main/java/com/example/akademise/AkademiseApi.java, android/Akademise_dev/app/src/main/java/com/example/akademise/Biography.java, android/Akademise_dev/app/src/main/java/com/example/akademise/Profile.java, android/Akademise_dev/app/src/main/java/com/example/akademise/ProfileFragment.java, android/Akademise_dev/app/src/main/java/com/example/akademise/ProfileOthersFragment.java, android/Akademise_dev/app/src/main/java/com/example/akademise/ProfileUpdate.java, android/Akademise_dev/app/src/main/java/com/example/akademise/SignupFragment.java, android/Akademise_dev/app/src/main/java/com/example/akademise/Upvote.java, android/Akademise_dev/app/src/main/java/com/example/akademise/UserInterest.java, android/Akademise_dev/app/src/main/res/layout/fragment_profile.xml, android/Akademise_dev/app/src/main/res/layout/fragment_signup.xml
Please review the code and merge with the branch _android-dev_ if possible.
=> Edit profile, Upvote and Follow functionalities are added.

frontend/src/pages/Home/index.jsx
* Homepage now displays content from both related interest tags and users followed by logged in user.
* Added disclaimer at the end of home page.
=> Homepage enhancements

frontend/src/pages/Home/index.jsx
- From one of the previous merges there are two declerations for a same variable. One of those declerations is removed.
- There was a missing comma it is added.
=> Frontend bug fix

android/Akademise_dev/app/src/main/java/com/example/akademise/ProjectCreationActivity.java, android/Akademise_dev/app/src/main/java/com/example/akademise/ProjectInfoEntryFragment.java, android/Akademise_dev/app/src/main/res/layout/fragment_project_info_entry_2.xml
Tags connected to backend while creating a new project and abstracts textbox's size adjusted to fit layout. 
Latest version of the android-dev branch merged with the android-projectcreation branch before doing this operation.
.gradle files not pushed so they can not cause any conflicts.
There are no other pushes during these changes so android-projectcreation branch can be merged without any conflict resolution.
=> Android projectcreation

backend/controllers/autoCompleteController.js
You can update your error handlings with this and commit to the backend_error_handling branch.
`res.status(500).send(error.message)`
=> Update error handling

frontend/src/components/PersonRecommendationCard/index.jsx, frontend/src/pages/ProjectDetails/index.jsx, frontend/src/pages/Search/index.jsx, frontend/src/redux/follow/api.js, frontend/src/redux/search/api.js
* Fixed bug on initial search, now when you are on another page you will directly get your results on search.
* Fixed bug on follow that exchanged followed user's profile data with the current user
* Fixed bug on privacy, now you can see public projects to which you aren't collaborating as public.
=> Frontend fix search bug

backend/controllers/homeController.js, backend/util/postUtil.js, backend/util/userUtil.js
User recommendations are now in this way:
- Users sharing similar interests
- Users with same universities
- Users with same departments
All 3 categories contain unique suggestions both among each other and in itself
Post recommendations could also send non unique Posts (Projects) in different categories, these are also fixed.
=> Updated user recommendations and post recommendations

frontend/src/pages/SignUp/index.jsx, frontend/src/pages/SignUp/style.js
User agreement is added to the last part of the sign up.
Screenshot:
=> Frontend User Agreement

frontend/src/pages/SignUp/index.jsx
I have implemented password validation with the following restraints:
- At least 8 characters
- At least one letter
- At least one number
- At least one symbol
=> Frontend password restraints

frontend/src/components/LandingHeader/index.jsx, frontend/src/pages/About/index.jsx, frontend/src/pages/About/style.js, frontend/src/pages/ListFollow/index.jsx, frontend/src/routes.jsx
I have added an about page.
I used a template text from `https://www.volusion.com/blog/how-to-build-an-about-us-page-with-examples/`
=> Frontend about page

backend/app.js, backend/controllers/autoCompleteController.js, backend/controllers/eventController.js, backend/routers/eventRouter.js
Event get&add endpoints are added.
Please review & merge, and upgrade if necessary.
Note that I use "akademise_test_3" database, for the version of relations and models,
Pls change your db from your .env configuration as well.
=> Backend event endpoints

backend/controllers/homeController.js, backend/model/db.js, backend/package-lock.json, backend/package.json, backend/routers/homeRouter.js
I added a simple home/delete endpoint and tested it with postman. Any review will be welcomed
=> add home/delete endpoint

backend/controllers/collabController.js, backend/controllers/notificationController.js, backend/routers/notificationRouter.js, backend/util/notificationUtil.js
Implemented notification related functions and changed old ones if it was necessary.Also fixed minor things.Please review.
=> Implemented notification related functions

backend/controllers/eventController.js, backend/model/db.js, backend/model/event_favs.js, backend/routers/eventRouter.js
I have written some new endpoints for backend, that allow the requester to search events based on fields, get a specific event and update one. I also improved endpoints that got implemented earlier to be more secure and also more readable. Any review is more than welcome.
=> Improved Event endpoints for Backend

backend/app.js, backend/package-lock.json, backend/package.json, backend/util/cron.js
Implemented a cron job that will run once a month, every first day of month at 00:00. It will delete the users that are not validated and older than a month.
#267 is the related issue.
=> Cron Job about non-validated users

backend/controllers/authController.js, backend/controllers/validateController.js, backend/routers/authRouter.js, backend/routers/validateRouter.js, backend/util/authCheck.js, backend/util/email.html, backend/util/mailController.js
4 new endpoints are added. 3 of them are used for password recovery operation, and other is for resetting known password.
An email is sent when a password recovery is requested, in that email there is a validation code. That validation code is given to server to retrieve a jwt that will allow the user to change their password. Then a password can be changed.
=> Password reset related endpoints

backend/controllers/eventController.js, backend/controllers/notificationController.js, backend/routers/notificationRouter.js
Added new router and function to be able to send notification to rejected users(whose collaboration request is rejected).Please review.
=> Improved design and added new function for rejection notifications

frontend/src/components/ProfileSider/index.jsx, frontend/src/pages/CreateEvent/index.jsx, frontend/src/pages/CreateEvent/style.js, frontend/src/redux/event/api.js, frontend/src/routes.jsx
Event creation page is ready.
Work done:
- event Page is implemented
- a create event button is added to the profile sider
- `/event/create` route is added
- a function to send create event requests is implemented
- backend connections are made
Screen Shot:
=> Frontend Event Creation Page

backend/model/db.js, backend/model/events.js, backend/model/projects.js, backend/package-lock.json, backend/package.json
I have changed variable types and some queries to make the code work for postgres database. #390
=> Migration to postgres

frontend/src/assets/user_agreement.jsx, frontend/src/pages/SignUp/index.jsx
Our user agreement did not have a part concerning KVKK so it was added.
I moved the agreement text to an asset file to improve readability.
I will post the updated text as another comment in this PR thread.
=> KVKK added to user agreement & user agreement moved into asset file

frontend/src/pages/EditEvent/index.jsx, frontend/src/pages/EditEvent/style.js, frontend/src/redux/event/api.js, frontend/src/routes.jsx
Event edit page is implemented.
Users can edit any field of the events. Page loads a page linke event creation page and fills the fields with the current values of the event. When user confirms edits, an update request is sent to the backend.
Fields that can be edited:
- type
- title
- body
- other (extra information)
- date
- location
- link
Screen Shot:
=> Frontend Event Edit Page is Created

android/Akademise_dev/app/src/main/java/com/example/akademise/AkademiseApi.java, android/Akademise_dev/app/src/main/java/com/example/akademise/MainActivity.java, android/Akademise_dev/app/src/main/java/com/example/akademise/Notifications.java, android/Akademise_dev/app/src/main/java/com/example/akademise/PopUpAdapter.java, android/Akademise_dev/app/src/main/res/layout/popup_row.xml
notification/get endpoint is used to get the notifications.
if you click on a notification, it is deleted. If you click on a name profile is shown. You can see requests and invitations, new followers, new collaborators.
=> notification system updated.

android/Akademise_dev/app/src/main/AndroidManifest.xml, android/Akademise_dev/app/src/main/java/com/example/akademise/AkademiseApi.java, android/Akademise_dev/app/src/main/java/com/example/akademise/EditProjectActivity.java, android/Akademise_dev/app/src/main/java/com/example/akademise/GetProjects.java, android/Akademise_dev/app/src/main/java/com/example/akademise/Project.java, android/Akademise_dev/app/src/main/java/com/example/akademise/ProjectCreationActivity.java, android/Akademise_dev/app/src/main/java/com/example/akademise/ProjectCreationActivity2.java, android/Akademise_dev/app/src/main/java/com/example/akademise/ProjectDetailsActivity.java, android/Akademise_dev/app/src/main/java/com/example/akademise/ProjectFragment.java, android/Akademise_dev/app/src/main/java/com/example/akademise/RecyclerViewDetailsAdapter.java, android/Akademise_dev/app/src/main/java/com/example/akademise/UpdateProject.java, android/Akademise_dev/app/src/main/res/layout/activity_project_details.xml, android/Akademise_dev/app/src/main/res/layout/content_row.xml, android/Akademise_dev/app/src/main/res/layout/fragment_project_info_entry.xml, android/Akademise_dev/app/src/main/res/layout/fragment_project_info_entry_2.xml, android/Akademise_dev/app/src/main/res/values/strings.xml
Since backend switched MySql to Postgre Sql, previous project related calls had some minor bugs. 
- Project's privacy field changed to boolean instead of integer.
- Unnecessary project fields removed to create a new project.
Improvements about the project creation and details:
- Adding a milestone while creating a project is added.
- Addition of unlisted tags into database while creating new project is added.
- Project details can show project milestones too.
- Tags in project details are prettified.
Things left to do:
- View for status and privacy in the project details will be changed to have a better view.
- Project details from other user perspective will be updated.
=> Project Fields are updated according to the feedback from Backend

frontend/src/axios.js, frontend/src/pages/Events/index.jsx, frontend/src/pages/Events/style.js, frontend/src/routes.jsx
I have implemented a page that shows all events as list.
Events have:
-title
-description
-location
-date
-type
Url: {base}/events
it will redirect event details when an event is clicked
Screenshot of page:
=> Frontend events list

frontend/src/components/ChangePasswordModal/index.jsx, frontend/src/components/ChangePasswordModal/style.js, frontend/src/components/DeleteAccountModal/index.jsx, frontend/src/components/DeleteAccountModal/style.js, frontend/src/components/LandingHeader/index.jsx, frontend/src/components/LandingHeader/style.js, frontend/src/components/MainHeader/index.jsx, frontend/src/components/MainHeader/style.js, frontend/src/index.css, frontend/src/pages/ForgotPassword/index.jsx, frontend/src/pages/ForgotPassword/style.js, frontend/src/routes.jsx
Following functionalities are added:
- User can change password when logged in from the settings icon on the top right menu
- User can use the functionality of "forgot password" with 3 step email verification method
- User can delete own account
=> Frontend forgot password delete account

backend/controllers/postController.js, backend/controllers/profileController.js, backend/util/userUtil.js
Some changes related to database and fixes were implemented.
=> Migration to postgres continuing

frontend/src/axios.js, frontend/src/components/MainHeader/index.jsx, frontend/src/components/Notification/index.jsx, frontend/src/components/ResponseNotification/index.jsx, frontend/src/components/ResponseNotification/style.js, frontend/src/pages/CreateProject/index.jsx, frontend/src/pages/ProjectDetails/index.jsx
Following functionalities are added:
-- Notifications
User can now see if invitaiton/join request is accepted or rejected
Project collaborators can now see if another collaborator is added to the project
User can now see if another user has started to follow him/her
User can now see if he is removed from the project as a collaborator
Collaborators can now see if another collaborator is removed from the project
Project owner can now remove collaborators from the project if he/she desires
=> Frontend accept reject notifications

backend/controllers/eventController.js, backend/routers/eventRouter.js
I have implemented a new endpoint to return the events a user has favorited. There is a query parameter of userId, that returns of that user's faves.
=> New Endpoint to Return Fav-ed Events of a User

backend/controllers/searchController.js, backend/util/searchUtil.js
Tag filtering implemented in search
=> add tag filter to search

android/Akademise_dev/app/src/main/java/com/example/akademise/AkademiseApi.java, android/Akademise_dev/app/src/main/java/com/example/akademise/ProjectDetailsActivity.java, android/Akademise_dev/app/src/main/java/com/example/akademise/ProjectDetailsUserActivity.java, android/Akademise_dev/app/src/main/java/com/example/akademise/RecyclerViewDetailsAdapter.java, android/Akademise_dev/app/src/main/java/com/example/akademise/RecyclerViewMilestoneAdapter.java, android/Akademise_dev/app/src/main/java/com/example/akademise/RecyclerViewTagAdapter.java, android/Akademise_dev/app/src/main/res/drawable/rectangle.xml, android/Akademise_dev/app/src/main/res/drawable/rowview_shape.xml, android/Akademise_dev/app/src/main/res/drawable/rowview_shape_lightgreen.xml, android/Akademise_dev/app/src/main/res/drawable/rowview_shape_white.xml, android/Akademise_dev/app/src/main/res/drawable/small_rectangle.xml, android/Akademise_dev/app/src/main/res/layout/activity_project_details.xml, android/Akademise_dev/app/src/main/res/layout/activity_project_details_u.xml, android/Akademise_dev/app/src/main/res/layout/content_row.xml, android/Akademise_dev/app/src/main/res/layout/milestone_row.xml, android/Akademise_dev/app/src/main/res/layout/tag_row.xml, android/Akademise_dev/app/src/main/res/values/colors.xml
Things accomplished:
- Project tags and milestones are shown in Recycler View seperately.
- Projects tags and milestone are more distinguisible.
- Summary and requirements can be scrolled if it has more contents than defined text box.
- Status view adjusted frontend colors.
- If the user is the collaborator of the project, 'Request Collaboration' button is changed to 'Leave Project'.
- Collaborator of the project can leave project.
=> Android Project Creation and Details view improvements

frontend/src/pages/Search/index.jsx, frontend/src/redux/search/api.js
I have successfully changed the search page to make use of the new endpoints introduced by the backend team after 
1. switching to postgreSQL
2. introducing semantic search
3. adding event search
=> Frontend Semantic Search

frontend/src/pages/EventDetails/index.jsx, frontend/src/pages/Events/index.jsx
"add to calendar" button redirects to google calendar to save event.
date format in list of events is more readable now.
=> add to calendar button created in event details and date format changes in events list

android/Akademise_dev/app/src/main/AndroidManifest.xml, android/Akademise_dev/app/src/main/java/com/example/akademise/InvitationActivity.java, android/Akademise_dev/app/src/main/java/com/example/akademise/ProfileFragment.java, android/Akademise_dev/app/src/main/java/com/example/akademise/RecyclerViewAdapterInvite.java, android/Akademise_dev/app/src/main/java/com/example/akademise/RequestInvitationActivity.java, android/Akademise_dev/app/src/main/res/layout/fragment_invitation.xml, android/Akademise_dev/app/src/main/res/layout/invite_row.xml
Project owner can send invitations to other users to join him in his project. 
Searching for users is also added
=> Sendind project invitations

android/Akademise_dev/app/src/main/AndroidManifest.xml, android/Akademise_dev/app/src/main/java/com/example/akademise/AddEvent.java, android/Akademise_dev/app/src/main/java/com/example/akademise/AddEventFragment.java, android/Akademise_dev/app/src/main/java/com/example/akademise/AkademiseApi.java, android/Akademise_dev/app/src/main/java/com/example/akademise/Event.java, android/Akademise_dev/app/src/main/java/com/example/akademise/EventActivity.java, android/Akademise_dev/app/src/main/java/com/example/akademise/EventAdapter.java, android/Akademise_dev/app/src/main/java/com/example/akademise/EventFilters.java, android/Akademise_dev/app/src/main/java/com/example/akademise/EventFragment.java, android/Akademise_dev/app/src/main/java/com/example/akademise/EventOperation.java, android/Akademise_dev/app/src/main/java/com/example/akademise/MainActivity.java, android/Akademise_dev/app/src/main/java/com/example/akademise/MyEventAdapter.java, android/Akademise_dev/app/src/main/java/com/example/akademise/MyEventsFragment.java, android/Akademise_dev/app/src/main/java/com/example/akademise/UpdateEvent.java, android/Akademise_dev/app/src/main/java/com/example/akademise/UpdateEventActivity.java, android/Akademise_dev/app/src/main/java/com/example/akademise/UpdateEventFragment.java, android/Akademise_dev/app/src/main/res/layout/activity_event.xml, android/Akademise_dev/app/src/main/res/layout/activity_my_events.xml, android/Akademise_dev/app/src/main/res/layout/activity_update_event.xml, android/Akademise_dev/app/src/main/res/layout/event_row.xml, android/Akademise_dev/app/src/main/res/layout/fragment_add_event.xml, android/Akademise_dev/app/src/main/res/layout/fragment_event.xml, android/Akademise_dev/app/src/main/res/layout/fragment_my_events.xml, android/Akademise_dev/app/src/main/res/layout/fragment_update_event.xml, android/Akademise_dev/app/src/main/res/layout/my_event_row.xml, android/Akademise_dev/app/src/main/res/menu/bottom_nav_menu.xml, android/Akademise_dev/app/src/main/res/values/strings.xml
=> Android event

frontend/src/components/MainHeader/index.jsx, frontend/src/components/SearchableTag/index.jsx, frontend/src/components/SearchableTag/style.js, frontend/src/pages/EventDetails/index.jsx, frontend/src/pages/Profile/index.jsx, frontend/src/pages/ProjectDetails/index.jsx, frontend/src/pages/ProjectDetails/style.js, frontend/src/pages/Search/index.jsx, frontend/src/redux/search/api.js
I have implemented the following functionalities:
* **Clickable project tags**, which direct the user to project search filtered with said tag and no query
* **Advanced search tab** on search page
This tab allows the user to enter a query of their choice, and tags of their choice to better search projects.
=> Frontend Tag Search

android/Akademise_dev/app/src/main/AndroidManifest.xml, android/Akademise_dev/app/src/main/java/com/example/akademise/InvitationActivity.java, android/Akademise_dev/app/src/main/java/com/example/akademise/InviteAdapter.java, android/Akademise_dev/app/src/main/java/com/example/akademise/ProfileFragment.java, android/Akademise_dev/app/src/main/java/com/example/akademise/ReceivedInvitationsActivity.java, android/Akademise_dev/app/src/main/java/com/example/akademise/RecyclerViewAdapterInvite.java, android/Akademise_dev/app/src/main/res/layout/activity_received_inv.xml, android/Akademise_dev/app/src/main/res/layout/fragment_profile.xml, android/Akademise_dev/app/src/main/res/layout/request_row.xml
Now user can see project invitations from other users, she can also accept / reject invitations
=> received invitations

backend/controllers/followController.js, backend/controllers/homeController.js, backend/controllers/searchController.js, backend/elastic/elasticUtil.js, backend/elastic/elastic_client.js, backend/routers/followRouter.js, backend/routers/homeRouter.js, backend/routers/searchRouter.js, backend/routers/validateRouter.js, backend/util/mailController.js, backend/util/searchUtil.js
=> comment the files I wrote

frontend/src/components/ContentCard/index.jsx, frontend/src/components/FilterButton/index.jsx, frontend/src/components/FilterButtonSmall/index.jsx, frontend/src/components/MainHeader/index.jsx, frontend/src/components/Notification/index.jsx, frontend/src/components/PersonRecommendationCard/index.jsx, frontend/src/components/ProfileSider/index.jsx, frontend/src/pages/Home/index.jsx, frontend/src/pages/ProjectDetails/index.jsx, frontend/src/pages/SavedEvents/index.jsx, frontend/src/pages/Search/index.jsx
Comments are added to the following pages and components.
Pages:
- Home Page
- Project Details Page
- Search Page
- Saved Events Page
Components:
- Profile Sider Component
- Content Card Component
- Filter Button Component
- Filter Button Small Component
- Main Header Component
- Notification Component
- Person Recommendation Component
=> Frontend comments

frontend/src/pages/ProjectDetails/index.jsx
Since the structure of the search enpoint is changed at the backend side, user selection modal of the batch invites is effected as well. Therefore it needed to be revised. Necessary connection revisions are made.
Screenshot:
=> Search Endpoint Connection of the Batch Invite User Selection Modal

frontend/src/pages/CreateEvent/index.jsx, frontend/src/pages/CreateProject/index.jsx, frontend/src/pages/EditEvent/index.jsx, frontend/src/redux/event/api.js
> Project and event creation bug is fixed bug was caused by a type change at the dabase. 
> isPublic field is changed to the boolean, before it was an integer value. After related changes both creation processes are working properly.
Appearently this was not cause any bugs, but I think it is still a good practice that keep variable types coherent.
A delete event button is added (to edit event page) and backend connections are made.
=> Frontend creation and edit enhancements
